version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - NODE_ENV=development
      - WATCHPACK_POLLING=true # Enable polling for file changes
      - CHOKIDAR_USEPOLLING=true # Enable polling for chokidar
    command: npm run dev
    networks:
      - fullstack-network
    # Optional: give it a container name
    container_name: web
networks:
  fullstack-network:
    external: true
